//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPPD_Dental_Clinic_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public int Dates_ID { get; set; }
        public int Patient_ID { get; set; }
        public System.DateTime Date1 { get; set; }
        public string Doctor_name { get; set; }
        public string Procedures { get; set; }
        public string Procedure_Comment { get; set; }
        public string Medication { get; set; }
        public string Supervisor_signature { get; set; }
        public int Virtual_ID { get; set; }
    
        public virtual Patient_info Patient_info { get; set; }
    }
}
