//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPPD_Dental_Clinic_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCEntities : DbContext
    {
        public DCEntities()
            : base("name=DCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Patient_info> Patient_info { get; set; }
        public DbSet<DiagnosisList> DiagnosisLists { get; set; }
        public DbSet<ProcedureList> ProcedureLists { get; set; }
        public DbSet<Date> Dates { get; set; }
        public DbSet<Diagnosis> Diagnoses { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<X_ray_images> X_ray_images { get; set; }
    }
}
