//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPPD_Dental_Clinic_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        public int Diagnose_ID { get; set; }
        public int Patient_ID { get; set; }
        public string Diagnose { get; set; }
        public string Treatment_Plan { get; set; }
        public int Virtual_ID { get; set; }
    
        public virtual Patient_info Patient_info { get; set; }
    }
}
