//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPPD_Dental_Clinic_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_info
    {
        public Patient_info()
        {
            this.Dates = new HashSet<Date>();
            this.Diagnoses = new HashSet<Diagnosis>();
            this.X_ray_images = new HashSet<X_ray_images>();
        }
    
        public int Patient_ID { get; set; }
        public string Patient_name { get; set; }
        public int Age { get; set; }
        public System.DateTime Visit_date { get; set; }
        public System.DateTime Birth_date { get; set; }
        public byte[] Patient_image { get; set; }
        public string Sex { get; set; }
        public string Home_number { get; set; }
        public string Phone_number { get; set; }
        public string Address { get; set; }
        public string Cheif_complaint { get; set; }
        public string Medical_alert { get; set; }
        public string Relative_marriage { get; set; }
        public double DMF { get; set; }
        public double C_dmf { get; set; }
        public double DEF { get; set; }
        public string Comments { get; set; }
        public Nullable<double> D_DMF { get; set; }
        public Nullable<double> M_DMF { get; set; }
        public Nullable<double> F_DMF { get; set; }
        public Nullable<double> dd_dmf { get; set; }
        public Nullable<double> mm_dmf { get; set; }
        public Nullable<double> ff_dmf { get; set; }
        public Nullable<double> D_DEF { get; set; }
        public Nullable<double> E_DEF { get; set; }
        public Nullable<double> F_DEF { get; set; }
    
        public virtual ICollection<Date> Dates { get; set; }
        public virtual ICollection<Diagnosis> Diagnoses { get; set; }
        public virtual ICollection<X_ray_images> X_ray_images { get; set; }
    }
}
